django CRUD site/CRUD/urls.py
from django.urls import path

from . import views
app_name="CRUD"
urlpatterns = [
    path('add/', views.index, name='index'),
    path('', views.home, name='home'),
    path('read/', views.read, name='read'),
    path('search/',views.search,name='search'),
    path('update/',views.update,name='update'),
    path('delete/',views.delete,name='delete'),

]

django CRUD site/myfirstsite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('CRUD/', include('CRUD.urls',namespace="CRUD")),
    path('admin/', admin.site.urls),
]

django CRUD site/CRUD/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    name=models.CharField(max_length=255)
    age=models.IntegerField()
    username=models.CharField(max_length=255)


    def __str__(self):
        return self.name

django CRUD site/CRUD/forms.py
from django.forms import ModelForm
from .models import Post

class NameForm(ModelForm):
    class Meta:
        model=Post
        fields=["username"]

class Form(ModelForm):
    class Meta:
        model=Post
        fields="__all__"

class DeleteNewForm(ModelForm):
    class Meta:
        model = Post
        fields = []

django CRUD site/CRUD/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.http import HttpResponse,HttpResponseRedirect
from .forms import NameForm,Form,DeleteNewForm
from .models import Post

def index(request):
    if request.method == 'POST':
        form = Form(request.POST)
        if form.is_valid():
            form_item=form.save(commit='false')
            form_item.save()
            return redirect('../')
    else:
        form = Form()

    return render(request, 'CRUD/index.html', {'form': form})

def home(request):
    return render(request,'CRUD/home.html')


def update(request):
    form=None
    item=get_object_or_404(Post,username=request.session['name'])
    form=Form(request.POST or None,instance=item)
    if form.is_valid():
        form.save()
        return redirect('../')
    return render(request, 'CRUD/update.html', {'form': form})


def search(request):
    form=None
    if request.method == 'POST':
        form = NameForm(request.POST)
        if form.is_valid():
            f=form.cleaned_data['username']
            item=get_object_or_404(Post,username=f)
            if not item is None:
                request.session['name']=f
                return redirect('../update')
            else:
                return redirect('../')
    else:
        form = NameForm()

    return render(request, 'CRUD/search.html', {'form': form})

def delete(request):
    if request.method == 'POST':
        form = NameForm(request.POST)
        if form.is_valid():
            f=form.cleaned_data['username']
            item=get_object_or_404(Post,username=f)
            if not item is None:
                form = DeleteNewForm(request.POST or None,instance=item)
                item.delete()
                return redirect("../")
            else:
                return redirect('../')
    else:
        form = NameForm()

    return render(request, 'CRUD/delete.html', {'form': form})



def read(request):
    if request.method == 'POST':
        form = NameForm(request.POST)
        if form.is_valid():
            f=form.cleaned_data['username']
            item=get_object_or_404(Post,username=f)
            if not item is None:
                form=Form(instance=item)
                #form.save()
            else:
                return redirect('../')

    else:
        form = NameForm()

    return render(request, 'CRUD/read.html', {'form': form})

django CRUD site/CRUD/templates/CRUD/delete.html
{%extends 'CRUD/home.html'%}
{%block content%}
<form method="POST" action="">
    <div class="form-group">
    {% csrf_token %}
    {{form}}
    </div>
    <input type="submit" class="btn btn-success" value="Delete">
</form>

{%endblock%}

django CRUD site/CRUD/templates/CRUD/home.html
<!DOCTYPE HTML>
<html>
<head>
<style>
.custom{
    height:90px;
}
</style>
<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    <title>Home</title></head>
<body style="margin:200px;"><div class="container" >
    {%block content%}
    <div class="row">
        <div class="col-sm-3 btn btn-success custom">
    <a style="color:white; font-size: 40px; text-decoration: none;" href="{% url 'CRUD:index'%}">Create</a></div>
    <div class="col-sm-3 btn btn-primary">
    <a style="color:white; font-size: 40px; text-decoration: none;" href="{% url 'CRUD:read'%}">Read</a></div>
    <div class="col-sm-3 btn btn-warning">
    <a style="color:white; font-size: 40px; text-decoration: none;" href="{% url 'CRUD:search'%}">Update</a></div>
    <div class="col-sm-3 btn btn-danger">
    <a style="color:white; font-size: 40px; text-decoration: none;" href="{% url 'CRUD:delete'%}">Delete</a></div>
</div>
    {%endblock%}
</div>
<footer style="color:red;">* Every time you perform a CRUD operation, Please check the admin panel! </footer>
</body>
</html>

django CRUD site/CRUD/templates/CRUD/index.html
{%extends 'CRUD/home.html'%}
{%block content%}

<form   method="POST" action="">


    {% csrf_token %}
<div class="form-group">
    {{form}}
</div>
    <input type="submit" class="btn btn-success" value="Submit">


</form>

{%endblock%}

django CRUD site/CRUD/templates/CRUD/read.html
{%extends 'CRUD/home.html'%}
{%block content%}
<form method="POST" action="">

    {% csrf_token %}
    <div class="form-group">
    {{form}}
    </div>
    <input type="submit" class="btn btn-success" value="Read">
</form>
<br>
{%for key in form%}

<h2>{{key.value}}</h2><br>

{%endfor%}


{%endblock%}

django CRUD site/CRUD/templates/CRUD/search.html
{%extends 'CRUD/home.html'%}
{%block content%}
<form method="POST" action="">
    {% csrf_token %}
    <div class="form-group">
    {{form}}
    </div>
    <input type="submit" class="btn btn-success" value="Search">
</form>

{%endblock%}

django CRUD site/CRUD/templates/CRUD/update.html
{%extends 'CRUD/home.html'%}
{%block content%}
<form method="POST" action="">
    <div class="form-group">
    {% csrf_token %}

    {{form}}
    </div>
    <input type="submit" class="btn btn-success" value="Update">
</form>

{%endblock%}